// YouTube upload kit for the tour, from the last render's scene timings (out/video/summary.json):
// title, description with chapters, tags, settings → store/youtube-tour.md.
// YouTube chapters: the first at 0:00, at least 3, each at least 10 s — scenes (~8 s) are grouped.
import fs from "node:fs";
import path from "node:path";
import { HERE } from "./lib.mjs";

const NAMES = { explorer: "Data Explorer", loader: "Data Loader", recyclebin: "Recycle Bin", showalldata: "Show All Data", apitester: "API Tester",
  metadata: "Metadata", relationships: "Relationships", schema: "Schema", solutions: "Solutions", automation: "Automation", apps: "Apps",
  envvars: "Environment Variables", translations: "Translations", licenses: "Users & Licenses", bu: "Business Units", security: "Security Audit",
  teams: "Teams", adoption: "Adoption", logins: "Login History", storage: "Storage" };
const STORE = "https://chromewebstore.google.com/detail/edieednbdaclheikneelkjfbckibhdgl";
const REPO = "https://github.com/zmissoum/colvio";

const run = JSON.parse(fs.readFileSync(path.join(HERE, "out", "video", "summary.json"), "utf8")).find(s => s.lang === "en");
if (!run?.sceneStarts) { console.error("render the EN tour first: node make-video.mjs --lang=en --no-clips"); process.exit(2); }
const mmss = (t) => `${Math.floor(t / 60)}:${String(Math.floor(t % 60)).padStart(2, "0")}`;

export function chapters(scenes, total, min = 10) {
  const out = [];
  for (const [i, s] of scenes.entries()) {
    const at = i === 0 ? 0 : Math.floor(s.at);
    const cur = out[out.length - 1];
    if (cur && at - cur.at < min) cur.keys.push(s.key); else out.push({ at, keys: [s.key] });
  }
  while (out.length > 1 && Math.floor(total) - out[out.length - 1].at < min) { const last = out.pop(); out[out.length - 1].keys.push(...last.keys); }
  return out;
}

const ch = chapters(run.sceneStarts, run.seconds);
const lines = ch.map(c => `${mmss(c.at)} ${c.keys.map(k => NAMES[k]).join(" · ")}`);
const md = `# YouTube upload kit — tour (\`tools/video/out/video/colvio_tour_en.mp4\`, ${mmss(run.seconds)})

Generated by \`node youtube-kit.mjs\` from the last EN render — re-run it after re-rendering the tour (timestamps move).

## Title

\`\`\`text
Colvio in 3 minutes — the free toolkit for Dynamics 365 & Dataverse
\`\`\`

## Description

\`\`\`text
Colvio is a free, open-source browser extension for Microsoft Dynamics 365 and Dataverse: 21 modules, right in your browser, on the session you're already signed in with. This tour shows 20 of them on demo data.

Chapters
${lines.join("\n")}

Chrome Web Store: ${STORE}
Source code: ${REPO}

No account, no app registration, no telemetry: Colvio talks only to your own Dynamics 365 org.

#Dynamics365 #Dataverse #PowerPlatform
\`\`\`

## Tags

\`\`\`text
Dynamics 365, Dataverse, Power Platform, Power Apps, D365, Dynamics 365 CRM, Chrome extension, Dataverse Web API, FetchXML, Dynamics 365 admin, Dynamics 365 tools, Colvio
\`\`\`

## Settings

- Thumbnail: \`store/youtube_thumbnail_1280x720.png\` (custom thumbnails need a phone-verified channel)
- Audience: **No, it's not made for kids**
- Category: Science & Technology · Video language: English
- Visibility: Public (or Unlisted — check that embedding is allowed: the Chrome Web Store promo video plays it)
- Then paste the video link in the Chrome Web Store dashboard → Store listing → promo video
`;
fs.writeFileSync(path.join(HERE, "..", "..", "store", "youtube-tour.md"), md);
console.log(`✓ store/youtube-tour.md — ${ch.length} chapters:\n${lines.join("\n")}`);
