// Adoption → PowerPoint report. Two layers:
//  - buildReportModel(): PURE — turns the screen's aggregates into slide content (unit-tested).
//  - exportAdoptionPptx(): thin renderer over pptxgenjs, dynamic-imported so the ~800 KB library
//    costs nothing until the button is clicked (same pattern as the lazy xlsx chunk).
// Charts are NATIVE PowerPoint charts — the recipient can restyle/edit them, they're not images.

const PALETTE = { ink: "1A1D26", mut: "4A5068", dim: "8890A4", vi: "0066FF", cy: "0891B2", gn: "059669", yw: "D97706", rd: "DC2626" };

/** Pure slide-content model — everything the deck shows, no pptx objects. */
export function buildReportModel({ orgName, windowRange, roleFilter, buLabel, interval, agg, failedDays = 0, nowMs, includeService = false }) {
  const fmt = (n) => (n ?? 0).toLocaleString("en-US");
  const filters = [roleFilter ? `Role: ${roleFilter}` : null, buLabel ? `BU: ${buLabel}` : null].filter(Boolean).join(" · ") || "All users";
  const e = agg.engagement || {};
  const kpis = [
    { label: "Access events", value: fmt(agg.total), hint: `≤1 event / user / ${interval} h (Dataverse)` },
    { label: "Distinct users", value: fmt(agg.unique), hint: `of ${fmt(agg.scopeCount)} enabled in scope` },
    { label: "Avg daily active users", value: (e.dauAvg ?? 0).toFixed(1), hint: "quiet days count as 0" },
    ...(e.wau != null ? [{ label: "WAU (last 7 d)", value: fmt(e.wau) }] : []),
    ...(e.mau != null ? [{ label: "MAU (last 30 d)", value: fmt(e.mau) }] : []),
    ...(e.stickiness != null ? [{ label: "Stickiness (DAU÷MAU)", value: `${(e.stickiness * 100).toFixed(0)}%` }] : []),
    { label: "Never signed in", value: fmt(agg.never.length), hint: "enabled human users, 0 events" },
  ];
  // Never-signed-in split by license — the license-cleanup angle.
  const byLic = new Map();
  for (const u of agg.never) { const k = u.calTypeLabel || "(unknown)"; byLic.set(k, (byLic.get(k) || 0) + 1); }
  const neverByLicense = [...byLic.entries()].sort((a, b) => b[1] - a[1]).slice(0, 8);
  // Inactivity counts, only for thresholds the window can honestly assert.
  const DAY = 86400000;
  const inact = [30, 60, 90].filter(th => windowRange.days >= th).map(th => ({
    th,
    n: (agg.scopeRows || []).filter(r => (r.last ? (nowMs - Date.parse(r.last)) / DAY >= th : true)).length,
  }));
  const BU_CAP = 15;
  const buRows = (agg.buRows || []).slice(0, BU_CAP);
  return {
    title: {
      org: orgName || "Dynamics 365",
      windowLabel: `${windowRange.from.slice(0, 10)} → ${windowRange.to.slice(0, 10)} (${windowRange.days} days)`,
      filters,
    },
    kpis,
    // The methodology note must match the toggle — the deck used to claim "excluded" even when
    // service accounts were INCLUDED in every number (audit finding).
    honesty: `Numbers are ACCESS EVENTS from Dataverse's user-access audit: logged at most once per user per ${interval} h interval — a stable activity proxy, not literal logins or clicks. Service accounts (non-interactive, S2S application users) are ${includeService ? "INCLUDED in these numbers (toggle was on)" : "excluded"}. Only rows within the org's audit retention are visible.${failedDays ? ` ${failedDays} day(s) failed to load and are EXCLUDED from totals.` : ""}`,
    trend: {
      labels: agg.series.map(s => s.label.slice(5)), // MM-DD
      events: agg.series.map(s => s.logins),
      users: agg.series.map(s => s.users),
      weekly: !!agg.weekly,
    },
    weekday: { labels: (agg.weekday || []).map(w => w.label), events: (agg.weekday || []).map(w => w.events) },
    bu: {
      labels: buRows.map(r => r.bu),
      rates: buRows.map(r => Math.round(r.rate * 100)),
      detail: buRows.map(r => `${r.active}/${r.enrolled}`),
      capped: (agg.buRows || []).length > BU_CAP ? (agg.buRows || []).length - BU_CAP : 0,
    },
    findings: {
      neverCount: agg.never.length,
      neverByLicense,
      inact,
      svcSilent: (agg.svcRows || []).filter(s => !s.logins).length,
      svcTotal: (agg.svcRows || []).length,
    },
  };
}

/** Render + download the deck. Lazy-imports pptxgenjs on first use. */
export async function exportAdoptionPptx(model, fileName) {
  const pptxgen = (await import("pptxgenjs")).default;
  const pptx = new pptxgen();
  pptx.layout = "LAYOUT_16x9";
  const W = 10, TXT = { fontFace: "Segoe UI", color: PALETTE.ink };

  // ── Slide 1: title ──
  let s = pptx.addSlide();
  s.addText("CRM Adoption Report", { ...TXT, x: 0.5, y: 1.6, w: W - 1, h: 0.9, fontSize: 40, bold: true });
  s.addText(model.title.org, { ...TXT, x: 0.5, y: 2.5, w: W - 1, h: 0.5, fontSize: 20, color: PALETTE.vi, bold: true });
  s.addText(`Window: ${model.title.windowLabel}    ·    Scope: ${model.title.filters}`, { ...TXT, x: 0.5, y: 3.1, w: W - 1, h: 0.4, fontSize: 13, color: PALETTE.mut });
  s.addText("Generated by Colvio — free, open-source toolkit for Dynamics 365 / Dataverse", { ...TXT, x: 0.5, y: 4.9, w: W - 1, h: 0.35, fontSize: 10, color: PALETTE.dim });

  // ── Slide 2: KPIs ──
  s = pptx.addSlide();
  s.addText("Key metrics", { ...TXT, x: 0.5, y: 0.3, w: W - 1, h: 0.5, fontSize: 24, bold: true });
  const cols = 3, boxW = (W - 1 - (cols - 1) * 0.25) / cols;
  model.kpis.slice(0, 6).forEach((k, i) => {
    const x = 0.5 + (i % cols) * (boxW + 0.25), y = 1.0 + Math.floor(i / cols) * 1.55;
    s.addShape(pptx.ShapeType.roundRect, { x, y, w: boxW, h: 1.35, fill: { color: "F5F6FA" }, line: { color: "D0D4DE", width: 0.75 }, rectRadius: 0.06 });
    s.addText(k.value, { ...TXT, x: x + 0.15, y: y + 0.12, w: boxW - 0.3, h: 0.55, fontSize: 28, bold: true, color: PALETTE.vi });
    s.addText(k.label, { ...TXT, x: x + 0.15, y: y + 0.68, w: boxW - 0.3, h: 0.3, fontSize: 12, color: PALETTE.ink });
    if (k.hint) s.addText(k.hint, { ...TXT, x: x + 0.15, y: y + 0.97, w: boxW - 0.3, h: 0.3, fontSize: 9, color: PALETTE.dim });
  });
  s.addText(model.honesty, { ...TXT, x: 0.5, y: 4.35, w: W - 1, h: 0.9, fontSize: 9.5, italic: true, color: PALETTE.mut });

  // ── Slide 3: trend (native charts — editable in PowerPoint) ──
  s = pptx.addSlide();
  s.addText(`Activity trend — per ${model.trend.weekly ? "week" : "day"}`, { ...TXT, x: 0.5, y: 0.3, w: W - 1, h: 0.5, fontSize: 24, bold: true });
  const axis = { catAxisLabelFontSize: 8, valAxisLabelFontSize: 9, valAxisMinVal: 0, dataLabelFontSize: 8, catAxisLabelRotate: model.trend.labels.length > 20 ? 45 : 0 };
  s.addChart(pptx.ChartType.bar, [{ name: "Access events", labels: model.trend.labels, values: model.trend.events }],
    { x: 0.5, y: 0.95, w: W - 1, h: 2.15, barDir: "col", chartColors: ["0066FF"], showLegend: false, showTitle: true, title: "Access events", titleFontSize: 11, ...axis });
  s.addChart(pptx.ChartType.line, [{ name: "Distinct users", labels: model.trend.labels, values: model.trend.users }],
    { x: 0.5, y: 3.25, w: W - 1, h: 2.15, chartColors: ["0891B2"], lineSize: 2, lineSmooth: false, showLegend: false, showTitle: true, title: "Distinct users", titleFontSize: 11, ...axis });

  // ── Slide 4: weekday profile + BU adoption ──
  s = pptx.addSlide();
  s.addText("Where and when", { ...TXT, x: 0.5, y: 0.3, w: W - 1, h: 0.5, fontSize: 24, bold: true });
  s.addChart(pptx.ChartType.bar, [{ name: "Events", labels: model.weekday.labels, values: model.weekday.events }],
    { x: 0.5, y: 1.0, w: 4.2, h: 4.1, barDir: "col", chartColors: ["0066FF"], showLegend: false, showTitle: true, title: "Access events by weekday", titleFontSize: 11, catAxisLabelFontSize: 9, valAxisLabelFontSize: 9, valAxisMinVal: 0 });
  s.addChart(pptx.ChartType.bar, [{ name: "Adoption %", labels: model.bu.labels, values: model.bu.rates }],
    { x: 5.0, y: 1.0, w: 4.5, h: 4.1, barDir: "bar", chartColors: ["059669"], showLegend: false, showValue: true, dataLabelFontSize: 8, showTitle: true, title: `Adoption rate by business unit (%)${model.bu.capped ? ` — top ${model.bu.labels.length}` : ""}`, titleFontSize: 11, catAxisLabelFontSize: 8, valAxisLabelFontSize: 9, valAxisMinVal: 0, valAxisMaxVal: 100 });

  // ── Slide 5: findings ──
  s = pptx.addSlide();
  s.addText("Findings", { ...TXT, x: 0.5, y: 0.3, w: W - 1, h: 0.5, fontSize: 24, bold: true });
  const bullets = [];
  bullets.push({ text: `${model.findings.neverCount.toLocaleString("en-US")} enabled human user(s) never signed in during the window.`, options: { color: model.findings.neverCount ? PALETTE.rd : PALETTE.gn, bullet: true, fontSize: 14 } });
  for (const i of model.findings.inact) bullets.push({ text: `${i.n.toLocaleString("en-US")} user(s) inactive for ${i.th} days or more.`, options: { color: PALETTE.yw, bullet: true, fontSize: 14 } });
  if (model.findings.svcTotal) bullets.push({ text: `${model.findings.svcSilent} of ${model.findings.svcTotal} service/application account(s) show ZERO activity — a silent integration can be a broken one.`, options: { color: model.findings.svcSilent ? PALETTE.yw : PALETTE.gn, bullet: true, fontSize: 14 } });
  s.addText(bullets, { ...TXT, x: 0.5, y: 0.95, w: W - 1, h: 1.7, valign: "top" });
  if (model.findings.neverByLicense.length) {
    s.addText("Never signed in — by license type (paid seats that never log in are the finding):", { ...TXT, x: 0.5, y: 2.8, w: W - 1, h: 0.35, fontSize: 13, bold: true });
    s.addTable(
      [[{ text: "License type", options: { bold: true, fill: { color: "F5F6FA" } } }, { text: "Users", options: { bold: true, fill: { color: "F5F6FA" } } }],
        ...model.findings.neverByLicense.map(([lic, n]) => [lic, String(n)])],
      { x: 0.5, y: 3.2, w: 5.5, colW: [4, 1.5], fontSize: 11, fontFace: "Segoe UI", color: PALETTE.ink, border: { type: "solid", color: "D0D4DE", pt: 0.5 }, rowH: 0.28 }
    );
  }

  await pptx.writeFile({ fileName });
}
